"use client";

import { useEffect, useMemo, useState } from "react";
import { Activity, ArrowUpRight, Globe2, Lightbulb, Radar, RefreshCw, Rss, TrendingUp } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

type NewsArticle = { id: number; title: string; source_url: string; source_name: string | null; provider: string; category: string; content: string; published_at: string | null };
const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";

export function DashboardContent() {
  const [articles, setArticles] = useState<NewsArticle[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const loadNews = async () => {
    setLoading(true); setError(null);
    try { const response = await fetch(`${API_URL}/news/latest?limit=12`); if (!response.ok) throw new Error("The live feed is unavailable."); setArticles(await response.json()); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "The live feed is unavailable."); }
    finally { setLoading(false); }
  };
  useEffect(() => { loadNews(); }, []);
  const categories = useMemo(() => Array.from(new Set(articles.map((article) => article.category))), [articles]);
  return <main className="flex-1 overflow-y-auto bg-[#081321]"><TopIntro onRefresh={loadNews} loading={loading}/><div className="grid gap-5 p-5 sm:p-8 xl:grid-cols-3"><LiveProblems articles={articles} loading={loading} error={error}/><Coverage articles={articles} categories={categories}/><LatestNews articles={articles}/><PipelineStatus count={articles.length}/></div></main>;
}

function TopIntro({ onRefresh, loading }: { onRefresh: () => Promise<void>; loading: boolean }) { return <div className="flex flex-col gap-4 border-b border-slate-800 px-5 py-7 sm:flex-row sm:items-end sm:justify-between sm:px-8"><div><p className="text-sm text-emerald-400">Live intelligence</p><h1 className="mt-1 text-2xl font-semibold tracking-tight sm:text-3xl">Global engineering signals.</h1><p className="mt-1 text-sm text-slate-400">Fresh reports from NewsAPI, GDELT, and ReliefWeb, normalized in ForgeAI.</p></div><Button onClick={onRefresh} disabled={loading}><RefreshCw size={16} className={`mr-2 ${loading ? "animate-spin" : ""}`}/>Refresh feed</Button></div>; }

function LiveProblems({ articles, loading, error }: { articles: NewsArticle[]; loading: boolean; error: string | null }) { return <Card className="xl:col-span-2"><CardHeader className="flex-row items-center justify-between"><div><CardTitle className="flex items-center gap-2"><Activity size={18} className="text-emerald-400"/>Live problems</CardTitle><CardDescription className="mt-2">Latest source-backed engineering signals</CardDescription></div><span className="rounded bg-emerald-400/10 px-2 py-1 text-xs text-emerald-300">{articles.length} live</span></CardHeader><CardContent>{loading ? <FeedMessage message="Loading normalized news…"/> : error ? <FeedMessage message={error}/> : articles.length === 0 ? <FeedMessage message="No articles have been ingested yet. Configure NEWSAPI_KEY or wait for the next scheduled collection."/> : <div className="overflow-x-auto"><table className="w-full min-w-[520px] text-left text-sm"><thead className="border-b border-slate-800 text-xs uppercase tracking-wider text-slate-500"><tr><th className="pb-3 font-medium">Signal</th><th className="pb-3 font-medium">Category</th><th className="pb-3 font-medium">Source</th><th className="pb-3"/></tr></thead><tbody>{articles.slice(0, 5).map((article) => <tr key={article.id} className="border-b border-slate-800/70 last:border-0"><td className="max-w-[260px] py-4 font-medium"><a className="hover:text-emerald-300" href={article.source_url} target="_blank" rel="noreferrer">{article.title}</a></td><td className="py-4"><span className="rounded bg-cyan-400/10 px-2 py-1 text-xs text-cyan-200">{article.category}</span></td><td className="py-4 text-slate-400">{article.source_name ?? article.provider}</td><td className="py-4 text-right"><a href={article.source_url} target="_blank" rel="noreferrer"><ArrowUpRight size={17} className="ml-auto text-slate-500"/></a></td></tr>)}</tbody></table></div>}</CardContent></Card>; }

function Coverage({ articles, categories }: { articles: NewsArticle[]; categories: string[] }) { return <Card className="relative overflow-hidden bg-[radial-gradient(circle_at_50%_35%,rgba(16,185,129,.16),transparent_42%)]"><CardHeader><CardTitle className="flex items-center gap-2"><Globe2 size={18} className="text-cyan-300"/>Global coverage</CardTitle><CardDescription className="mt-2">Sources and categories in the current feed</CardDescription></CardHeader><CardContent><div className="grid h-52 content-center gap-4 rounded-xl border border-slate-700/70 bg-slate-950/50 p-5"><div className="flex items-end gap-2">{["newsapi", "gdelt", "reliefweb"].map((provider) => { const count = articles.filter((article) => article.provider === provider).length; return <div key={provider} className="flex-1 text-center"><div className="mx-auto mb-2 rounded-t bg-gradient-to-t from-emerald-500 to-cyan-300" style={{ height: `${Math.max(8, count * 16)}px` }}/><p className="text-[10px] uppercase text-slate-500">{provider}</p><p className="text-sm font-medium">{count}</p></div>; })}</div><div className="flex flex-wrap gap-1.5">{categories.slice(0, 5).map((category) => <span key={category} className="rounded border border-slate-700 px-2 py-1 text-[10px] text-slate-400">{category}</span>)}</div></div></CardContent></Card>; }

function LatestNews({ articles }: { articles: NewsArticle[] }) { return <Card className="xl:col-span-2"><CardHeader><CardTitle className="flex items-center gap-2"><Rss size={18} className="text-amber-300"/>Incoming reports</CardTitle><CardDescription className="mt-2">The newest normalized reports available to the analysis pipeline</CardDescription></CardHeader><CardContent><div className="space-y-3">{articles.slice(5, 8).map((article) => <a key={article.id} href={article.source_url} target="_blank" rel="noreferrer" className="block rounded-xl border border-slate-800 bg-slate-950/30 p-4 transition-colors hover:border-emerald-400/40"><p className="font-medium">{article.title}</p><p className="mt-2 text-xs text-slate-500">{article.provider} · {article.category} · {article.published_at ? new Date(article.published_at).toLocaleString() : "Recently ingested"}</p></a>)}{articles.length <= 5 && <FeedMessage message="Incoming reports will appear as the live feed grows."/>}</div></CardContent></Card>; }

function PipelineStatus({ count }: { count: number }) { return <Card><CardHeader><CardTitle className="flex items-center gap-2"><TrendingUp size={18} className="text-violet-300"/>Pipeline status</CardTitle><CardDescription className="mt-2">Collection is separate from AI analysis</CardDescription></CardHeader><CardContent><div className="space-y-5"><Metric label="Stored signals" value={String(count)}/><Metric label="Connected providers" value="3"/><Metric label="AI analysis" value="Not enabled"/><div className="rounded-lg border border-dashed border-slate-700 p-3 text-xs leading-5 text-slate-500"><Lightbulb size={14} className="mb-1 text-amber-300"/>News is live. GPT-powered engineering recommendations remain intentionally disabled.</div></div></CardContent></Card>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between border-b border-slate-800 pb-3 text-sm"><span className="text-slate-400">{label}</span><span className="font-medium">{value}</span></div>; }
function FeedMessage({ message }: { message: string }) { return <div className="rounded-xl border border-dashed border-slate-700 bg-slate-950/30 p-7 text-center text-sm leading-6 text-slate-500">{message}</div>; }
