import { Activity, ArrowUpRight, Globe2, Lightbulb, Radar, TrendingUp } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

const problems = [
  ["Critical", "Urban heat stress", "South Asia", "+18%"],
  ["High", "Grid resilience", "Southern Europe", "+12%"],
  ["High", "Water scarcity", "East Africa", "+9%"],
];

export function DashboardContent() { return <main className="flex-1 overflow-y-auto bg-[#081321]"><TopIntro/><div className="grid gap-5 p-5 sm:p-8 xl:grid-cols-3"><LiveProblems/><MapPlaceholder/><Recommendations/><InnovationGap/></div></main>; }

function TopIntro() { return <div className="flex flex-col gap-4 border-b border-slate-800 px-5 py-7 sm:flex-row sm:items-end sm:justify-between sm:px-8"><div><p className="text-sm text-emerald-400">Monday, July 20</p><h1 className="mt-1 text-2xl font-semibold tracking-tight sm:text-3xl">Good morning, Alex.</h1><p className="mt-1 text-sm text-slate-400">Here’s where engineering can make the biggest difference today.</p></div><Button><Radar size={16} className="mr-2"/>Explore signals</Button></div>; }

function LiveProblems() { return <Card className="xl:col-span-2"><CardHeader className="flex-row items-center justify-between"><div><CardTitle className="flex items-center gap-2"><Activity size={18} className="text-emerald-400"/>Live problems</CardTitle><CardDescription className="mt-2">High-impact challenges gaining momentum</CardDescription></div><button className="text-sm text-emerald-400 hover:text-emerald-300">View all</button></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[460px] text-left text-sm"><thead className="border-b border-slate-800 text-xs uppercase tracking-wider text-slate-500"><tr><th className="pb-3 font-medium">Signal</th><th className="pb-3 font-medium">Region</th><th className="pb-3 font-medium">Momentum</th><th className="pb-3"/></tr></thead><tbody>{problems.map(([level, signal, region, movement]) => <tr key={signal} className="border-b border-slate-800/70 last:border-0"><td className="py-4"><span className={`mr-2 rounded px-1.5 py-1 text-[10px] font-bold uppercase ${level === "Critical" ? "bg-rose-500/15 text-rose-300" : "bg-amber-500/15 text-amber-300"}`}>{level}</span><span className="font-medium">{signal}</span></td><td className="py-4 text-slate-400">{region}</td><td className="py-4 text-emerald-400">{movement}</td><td className="py-4 text-right"><ArrowUpRight size={17} className="ml-auto text-slate-500"/></td></tr>)}</tbody></table></div></CardContent></Card>; }

function MapPlaceholder() { return <Card className="relative overflow-hidden bg-[radial-gradient(circle_at_50%_35%,rgba(16,185,129,.16),transparent_42%)]"><CardHeader><CardTitle className="flex items-center gap-2"><Globe2 size={18} className="text-cyan-300"/>Global map</CardTitle><CardDescription className="mt-2">Active problem clusters</CardDescription></CardHeader><CardContent><div className="relative grid h-52 place-items-center overflow-hidden rounded-xl border border-slate-700/70 bg-slate-950/50"><div className="absolute h-40 w-72 rounded-[50%] border border-cyan-400/20"/><div className="absolute h-28 w-48 rounded-[50%] border border-cyan-400/20"/><span className="absolute left-[23%] top-[37%] h-3 w-3 animate-pulse rounded-full bg-rose-400 shadow-[0_0_18px_4px_rgba(251,113,133,.35)]"/><span className="absolute right-[27%] top-[25%] h-2.5 w-2.5 rounded-full bg-amber-300 shadow-[0_0_18px_4px_rgba(253,224,71,.35)]"/><span className="absolute bottom-[28%] right-[42%] h-2.5 w-2.5 rounded-full bg-emerald-400 shadow-[0_0_18px_4px_rgba(52,211,153,.35)]"/><p className="mt-36 text-xs text-slate-500">Interactive map — coming next</p></div></CardContent></Card>; }

function Recommendations() { return <Card className="xl:col-span-2"><CardHeader><CardTitle className="flex items-center gap-2"><Lightbulb size={18} className="text-amber-300"/>Engineering recommendations</CardTitle><CardDescription className="mt-2">Concepts matched to the most urgent global signals</CardDescription></CardHeader><CardContent><div className="rounded-xl border border-dashed border-slate-700 bg-slate-950/30 p-7 text-center"><p className="font-medium text-slate-200">Your opportunity pipeline will appear here.</p><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">Once analysis is connected, ForgeAI will surface solution directions, feasibility signals, and next steps.</p></div></CardContent></Card>; }

function InnovationGap() { return <Card><CardHeader><CardTitle className="flex items-center gap-2"><TrendingUp size={18} className="text-violet-300"/>Innovation gap</CardTitle><CardDescription className="mt-2">Opportunity versus solution activity</CardDescription></CardHeader><CardContent><div className="space-y-5">{[["Climate adaptation", "82"], ["Circular materials", "67"], ["Resilient infrastructure", "54"]].map(([name, score]) => <div key={name}><div className="mb-2 flex justify-between text-sm"><span>{name}</span><span className="text-slate-400">{score}/100</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-gradient-to-r from-violet-500 to-emerald-400" style={{ width: `${score}%` }}/></div></div>)}</div></CardContent></Card>; }
